name: Bug Report
description: Report a bug in sslpin
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug clearly
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the issue
      placeholder: |
        1. Run 'sslpin example.com'
        2. See error...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - Node.js version:
        - sslpin version:
