name: Feature Request
description: Suggest a new feature or improvement
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this feature be useful?
      placeholder: This would help with...
    validations:
      required: false
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples if applicable
    validations:
